#!/bin/bash -x
#
# Commands to run after startup of bt_speaker

# Disable simple secure pairing
btmgmt ssp off

# Tell that bluetooth is readyy
espeak-ng -s 120 'bluetooth ready.
pin code is'

# Get configured PIN
PIN=$(awk -F "=" '/pin_code/ {print $2}' /etc/bt_speaker/config.ini | sed 's/ //g')

# Tell PIN code
for (( i=0; i<${#PIN}; i++ )); do
  echo "${PIN:$i:1}"
  espeak-ng -s 120 "${foo:$i:1}"
done
